spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    baseline-version: 0
  data:
    redis:
      connect-timeout: 3000
      timeout: 1000
---
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/migration/local
  cloud:
    vault:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 63790
